---
##########
# Java 8 #
##########
- name: Test if Java 8 is already installed
  win_stat:
      path: 'C:\Program Files\Java\jdk8u144-b01'
  register: java8_installed
  tags: Java8

- name: Check if Java 8 is already downloaded
  win_stat:
      path: 'C:\temp\jdk8u144-b01.zip'
  register: java8_download
  tags: Java8

- name: Download Java 8
  win_get_url:
    url: https://github.com/AdoptOpenJDK/openjdk8-releases/releases/download/jdk8u144-b01/OpenJDK8_x64_Win_jdk8u144-b01.zip
    dest: 'C:\temp\jdk8u144-b01.zip'
  when: (java8_download.stat.exists == false) and (java8_installed.stat.exists == false)
  tags: Java8

- name: Install Java 8
  win_unzip:
    src: C:\temp\jdk8u144-b01.zip
    dest: C:\Program Files\Java
  when: (java8_installed.stat.exists == false)
  tags: Java8

- name: Test if Java 8 symlink is already created
  win_stat:
      path: 'C:\openjdk\jdk8'
  register: java8_symlink
  tags: Java8

- name: Create symlink to Java 8
  raw: cmd /c mklink /D "C:\openjdk\jdk8\" "C:\Program Files\Java\jdk8u144-b01\"
  when: (java8_symlink.stat.exists == false)
  tags: Java8

- name: Set JAVA_HOME to version 8
  win_path:
    name: JAVA_HOME
    elements:
      - 'C:\Program Files\Java\jdk8u144-b01'
    scope: machine
    state: present
  when: (java8_installed.stat.exists == false)
  tags: Java8

- name: Add JAVA_HOME/bin to Path
  win_path:
    name: Path
    elements:
      - 'C:\Program Files\Java\jdk8u144-b01\bin'
    scope: machine
    state: present
  tags: Java8
