---
###########
# Crontab #
###########
- name: Add cron job to check for updates
  cron: name="Check for updates everyday at 1am"
        weekday="*"
        minute="0"
        hour="1"
        user=root
        job="{{ crontab_Patching }}"
        state=present
  tags: crontab
