---
##################
# Install Java 8 #
##################

# Install Java in a /usr/lib64/jvm/java-* directory and ensure is unique
# and it is listed first in alphabetic order.

- name: Test if IBM Java 8 is already installed
  stat:
    path: /usr/lib64/jvm/java-1.8.0-ibm-sdk-8.0-5.37/java/bin
  register: java8_installed
  when:
    - ansible_distribution == "SLES"
  tags: default_java8_SLES

- name: Download IBM Java 8
  get_url:
    url: https://public.dhe.ibm.com/ibmdl/export/pub/systems/cloud/runtimes/java/8.0.5.37/linux/{{ ansible_architecture }}/ibm-java-sdk-8.0-5.37-{{ ansible_architecture }}-archive.bin 
    dest: /tmp/ibm-java8.bin
    validate_certs: no
    force: no
  when:
    - ansible_distribution == "SLES"
    - java8_installed.stat.exists == false
  tags: default_java8_SLES

- name: Create IBM Java 8 response file
  shell: |
    echo "INSTALLER_UI=silent" > /tmp/ibm-java8.response.properties
    echo "USER_INSTALL_DIR=/usr/lib64/jvm/java-1.8.0-ibm-sdk-8.0-5.37" >> /tmp/ibm-java8.response.properties
    echo "LICENSE_ACCEPTED=TRUE" >> /tmp/ibm-java8.response.properties
  when:
    - ansible_distribution == "SLES"
    - java8_installed.stat.exists == false
  tags: default_java8_SLES

- name: Install Java 8
  shell: |
    mkdir -p /usr/lib64/jvm/java-1.8.0-ibm-sdk-8.0-5.37
    chmod +x /tmp/ibm-java8.bin
    /tmp/ibm-java8.bin -i silent -f /tmp/ibm-java8.response.properties
  when:
    - ansible_distribution == "SLES"
    - java8_installed.stat.exists == false
  tags: default_java8_SLES

# Set IBM Java 8 the default java on the system

- name: Add IBM Java 8 to alternatives
  shell: alternatives --install /usr/bin/java java /usr/lib64/jvm/java-1.8.0-ibm-sdk-8.0-5.37/bin/java 1
  when:
    - ansible_distribution == "SLES"
    - java8_installed.stat.exists == False
  tags: default_java8_SLES

- name: Set IBM Java 8 as default java
  alternatives:
    name: java
    path: /usr/lib64/jvm/java-1.8.0-ibm-sdk-8.0-5.37/bin/java
  when:
    - ansible_distribution == "SLES"
    - java8_installed.stat.exists == False
  tags: default_java8_SLES

# Clean up

- name: Remove downloaded packages for IBM Java 8
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /tmp/ibm-java8.bin
    - /tmp/ibm-java8.response.properties
  ignore_errors: True
  when:
    - ansible_distribution == "SLES"
    - java8_installed.stat.exists == False
  tags: default_java8_SLES
