###################################
# AdoptOpenJDK - Ansible Playbook #
###################################
- hosts:
    - build
    - test
    - "!*zos*"
    - "!*win*"
    - "!*macos*"
    - "!*aix*"
  gather_facts: yes
  tasks:

  #########
  # Roles #
  #########
  roles:
    - Debug
    - Common
    - Jenkins_User
    - Ant-Contrib
    - ccache
    - GIT_Source
    - CPAN
    - cmake
    - Docker
    - NVidia_Cuda_Toolkit
    - Superuser
    - Swap_File
    - Crontab
    - x11
    - NTP_TIME
    - gcc_48
    - Nagios_Plugins
    - Nagios_Master_Config
    - Nagios_Tunnel
    - Clean_Up
    - Security
    - Vendor
