---
###################################
# AdoptOpenJDK - Ansible Playbook #
###################################
- hosts: "{{ groups['Vendor_groups'] | default('localhost:build:test:!*zos*:!*win*:!*macos*:!*aix*') }}"
  gather_facts: yes
  tasks:

  #########
  # Roles #
  #########
  roles:
    - Debug
    - Version
    - Common
    - autoconf
    - curl
    - Jenkins_User
    - freemarker
    - ant
    - Ant-Contrib
    - ccache
    - GIT_Source
    - CPAN
    - cmake
    - gmake
    - Docker
    - NVidia_Cuda_Toolkit
    - Superuser
    - Swap_File
    - Crontab
    - x11
    - NTP_TIME
    - gcc_48
    - gcc_7
    - {role: nasm, when: ansible_architecture == 'x86_64'}
    - adoptopenjdk9
    - adoptopenjdk10
    - OpenSSL
    - Protobuf
    - Nagios_Plugins
    - Nagios_Master_Config
    - Nagios_Tunnel
    - Clean_Up
    - Security
    - Vendor
