---
##################
# Nagios_Plugins #
##################
- debug: msg='Installing Nagios plugins'

- name: If Raspbian on armv7l override ansible_distribution
  set_fact:
    ansible_distribution: "Ubuntu"
  when:
    - ansible_distribution == "Debian"
    - ansible_architecture == "armv7l"
    
  ###############
  # Nagios user #
  ###############
- name: Create Nagios user
  action: user name=nagios state=present shell=/bin/bash
  ignore_errors: yes
  when:
    - Nagios_Plugins == "Enabled"
  tags: nagios_plugins

- name: Set authorized key for Nagios user
  authorized_key:
    user: nagios
    state: present
    key: "{{ lookup('file', '{{ Nagios_User_SSHKey }}') }}"
  when:
    - Nagios_Plugins == "Enabled"
  tags: nagios_plugins

  ################################
  # Require OS specific playbook #
  ################################
- name: Include Nagios Playbook
  include_tasks: nagios_{{ ansible_distribution }}.yml
  when:
    - Nagios_Plugins == "Enabled"
  tags: nagios_plugins

  ##############################
  # Install additional plugins #
  ##############################
- name: Download add-on check_mem plugin
  get_url:
    url: https://raw.githubusercontent.com/justintime/nagios-plugins/master/check_mem/check_mem.pl
    dest: /usr/local/nagios/libexec/check_mem
    mode: 0755
  when:
    - Nagios_Plugins == "Enabled"
  tags: nagios_plugins
