#######################################################################################
# AdoptOpenJDK - Ansible Playbook to install Nagios plugins on RHEL 7 on x86 hardware #
#######################################################################################

###########################################################################
# License Information:                                                    #
# Nagios core and its plugins are lincesed under GPL                      #
# For more information please see: https://www.nagios.com/legal/licenses/ #
###########################################################################

  ###############
  # Nagios user #
  ###############
  - name: Allow Nagios to use yum while restricting it to check-update only
    shell: |
      echo "nagios ALL = NOPASSWD: /usr/bin/yum --security check-update" >> /etc/sudoers
    tags: nagios_plugins

  ##############################
  # Install additional plugins #
  ##############################
  - name: Download add-on check_yum plugin
    get_url:
      url: https://raw.githubusercontent.com/AdoptOpenJDK/openjdk-infrastructure/master/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Nagios_Plugins/tasks/additional_plugins/check_yum
      dest: /usr/local/nagios/libexec/check_yum
      mode: 0755
    tags: nagios_plugins
