#####################################################################################
# AdoptOpenJDK - Ansible Playbook to install Nagios plugins on SLES on x86 hardware #
#####################################################################################

###########################################################################
# License Information:                                                    #
# Nagios core and its plugins are lincesed under GPL                      #
# For more information please see: https://www.nagios.com/legal/licenses/ #
###########################################################################

  ########################################
  # Install Nagios dependencies packages #
  ########################################
  - name: Install additional packages used by Nagios
    package: "name={{ item }} state=latest"
    with_items:
      - fping
      - gcc
      - make
      - xinetd
    tags: nagios_plugins

  ###############
  # Nagios user #
  ###############
  - name: Allow Nagios to use zypper while restricting it to check-update only
    shell: |
      echo "nagios ALL = NOPASSWD: /usr/bin/zypper ref" >> /etc/sudoers
      echo "nagios ALL = NOPASSWD: /usr/bin/zypper list-patches" >> /etc/sudoers
    tags: nagios_plugins

  ##############################
  # Install additional plugins #
  ##############################
  - name: Download add-on check_zypper plugin
    get_url:
      url: https://raw.githubusercontent.com/AdoptOpenJDK/openjdk-infrastructure/master/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Nagios_Plugins/tasks/additional_plugins/check_zypper
      dest: /usr/local/nagios/libexec/check_zypper
      mode: 0755
    tags: nagios_plugins
