#########################################################################################
# AdoptOpenJDK - Ansible Playbook to install Nagios plugins on CentOS 7 on x86 hardware #
#########################################################################################

###########################################################################
# License Information:                                                    #
# Nagios core and its plugins are lincesed under GPL                      #
# For more information please see: https://www.nagios.com/legal/licenses/ #
###########################################################################

  ###############
  # Nagios user #
  ###############
  - name: Allow Nagios to use pkg while restricting it to audit only
    shell: |
      echo "nagios ALL = NOPASSWD: /usr/sbin/pkg audit -F" >> /etc/sudoers
    tags: nagios_plugins

  - name: Allow Nagios to use pkg while restricting it to upgrade --dry-run only
    shell: |
      echo "nagios ALL = NOPASSWD: /usr/sbin/pkg upgrade --dry-run" >> /etc/sudoers
    tags: nagios_plugins

  ##############################
  # Install additional plugins #
  ##############################
  - name: Download add-on check_pkg plugin
    get_url:
      url: https://raw.githubusercontent.com/AdoptOpenJDK/openjdk-infrastructure/master/ansible/playbooks/AdoptOpenJDK_Linux_Playbook/roles/Nagios_Plugins/tasks/additional_plugins/check_pkg
      dest: /usr/local/nagios/libexec/check_pkg
      mode: 0755
    tags: nagios_plugins
