---
##########
# gcc_48 #
##########
- name: Check if gcc-4.8 is installed on x86_64 RedHat 6
  shell: /usr/bin/gcc-4.8 >/dev/null 2>&1
  ignore_errors: yes
  register: gcc_installed
  tags: gcc-4.8

# MPC - gcc prerequisites
- name: Download mpc sources
  get_url:
    url: http://www.multiprecision.org/downloads/mpc-0.8.1.tar.gz
    dest: '/tmp/mpc-0.8.1.tar.gz'
    force: no
    mode: 0755
  when:
    - gcc_installed.rc != 0
    - ansible_distribution == "RedHat"
    - ansible_distribution_major_version == "6"
    - ansible_architecture == "x86_64"
  tags: gcc-4.8

- name: Extract mpc
  unarchive:
    src: /tmp/mpc-0.8.1.tar.gz
    dest: /tmp/
    copy: False
  when:
    - gcc_installed.rc != 0
    - ansible_distribution == "RedHat"
    - ansible_distribution_major_version == "6"
    - ansible_architecture == "x86_64"
  tags: gcc-4.8

- name: Running configure, compile and install for mpc
  shell: cd /tmp/mpc-0.8.1 && ./configure && make -j {{ ansible_processor_vcpus }} && make install
  when:
    - gcc_installed.rc != 0
    - ansible_distribution == "RedHat"
    - ansible_distribution_major_version == "6"
    - ansible_architecture == "x86_64"
  tags: gcc-4.8

# gcc
- name: Download gcc-4.8.5 source
  get_url:
    url: http://gnu.mirror.globo.tech/gcc/gcc-4.8.5/gcc-4.8.5.tar.gz
    dest: '/tmp/gcc-4.8.5.tar.gz'
    force: no
    mode: 0755
  when:
    - gcc_installed.rc != 0
    - ansible_distribution == "RedHat"
    - ansible_distribution_major_version == "6"
    - ansible_architecture == "x86_64"
  tags: gcc-4.8

- name: Extract gcc
  unarchive:
    src: /tmp/gcc-4.8.5.tar.gz
    dest: /tmp/
    copy: False
  when:
    - gcc_installed.rc != 0
    - ansible_distribution == "RedHat"
    - ansible_distribution_major_version == "6"
    - ansible_architecture == "x86_64"
  tags: gcc-4.8

- name: Running configure, compile and install for gcc-4.8.5
  shell: cd /tmp/gcc-4.8.5 && ./configure --prefix=/opt/gcc-4.8.5 && make -j {{ ansible_processor_vcpus }} && make -j {{ ansible_processor_vcpus }} install
  when:
    - gcc_installed.rc != 0
    - ansible_distribution == "RedHat"
    - ansible_distribution_major_version == "6"
    - ansible_architecture == "x86_64"
  tags: gcc-4.8

# Create symlinks
- name: Create symlink for gcc-4.8
  file:
    src: /opt/gcc-4.8.5/bin/gcc
    dest: /usr/bin/gcc-4.8
    owner: root
    group: root
    state: link
  when:
    - gcc_installed.rc != 0
    - ansible_distribution == "RedHat"
    - ansible_distribution_major_version == "6"
    - ansible_architecture == "x86_64"
  tags: gcc-4.8

- name: Create symlink for g++-4.8
  file:
    src: /opt/gcc-4.8.5/bin/g++
    dest: /usr/bin/g++-4.8
    owner: root
    group: root
    state: link
  when:
    - gcc_installed.rc != 0
    - ansible_distribution == "RedHat"
    - ansible_distribution_major_version == "6"
    - ansible_architecture == "x86_64"
  tags: gcc-4.8
