---
##########
# macOS #
##########

# Command Build Tool Packages

Build_Tool_Packages:
  - autoconf
  - bash # OpenJ9 needs bash v4 or later
  - coreutils
  - gnu-tar
  - nasm # openj9 jdk13+
  - wget

Build_Tool_Casks:
  - adoptopenjdk8
  - adoptopenjdk11

Test_Tool_Packages:
  - mercurial
  - pulseaudio
  - cpanminus

Test_Tool_Casks:
  - xquartz
