---
##########
# Ubuntu #
##########

# Command Build Tool Packages
Build_Tool_Packages:
  - autoconf
  - bison
  - build-essential
  - cpanminus
  - cpio
  - curl
  - flex
  - g++
  - gcc
  - gettext
  - libasound2-dev
  - libcups2-dev
  - libcurl4-openssl-dev
  - libdwarf-dev
  - libelf-dev
  - libexpat1-dev
  - libffi-dev
  - libfreetype6-dev
  - libfontconfig1-dev
  - libgmp3-dev
  - libmpfr4
  - libmpfr4-dbg
  - libmpfr-dev
  - libmpfr-doc
  - libwww-perl
  - libx11-dev
  - libxext-dev
  - libxrender-dev
  - libxt-dev
  - libxtst-dev
  - make
  - ntp
  - openjdk-7-jdk
  - openjdk-8-jdk
  - pkg-config
  - wget
  - zip

gcc_compiler:
  - g++-4.8
  - gcc-4.8

Additional_Build_Tools_x86_64:
  - zulu-9
  - libnuma-dev

Additional_Build_Tools_ppc64le:
  - libnuma-dev

Additional_Build_Tools_aarch64:
  - libpng-dev

Test_Tool_Packages:
  - acl
  - ant
  - ant-contrib
  - mercurial
  - perl
  - xauth
  - xorg
  - xvfb

Test_Tool_Packages_x86_64:
  - pulseaudio

crontab_Patching: "/usr/bin/apt-get update && /usr/bin/apt-get -y upgrade"
